//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int id { get; set; }
        public int userId { get; set; }
        public string name { get; set; }
        public System.DateTime startTime { get; set; }
        public System.DateTime endTime { get; set; }
        public string note { get; set; }
        public Nullable<int> typeId { get; set; }
        public int repeatRateId { get; set; }
        public bool isDone { get; set; }
    
        public virtual RepeatRate RepeatRate { get; set; }
        public virtual TaskType TaskType { get; set; }
        public virtual User User { get; set; }
    }
}
